CollegeERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
import apis.views as api_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('info/', include('info.urls')),
    path('api/department/', include('apis.urls')),

    path('api/bus/1/route/', api_view.UpRouteBusScheduleByDayView.as_view()),
    path('api/bus/2/route/', api_view.DownRouteBusScheduleByDayView.as_view()),
    path('api/bus/', api_view.RouteAll.as_view()),

    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='authentication/login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='authentication/logout.html'), name='logout'),


    #__________________Django Toolbar________________
    #path("__debug__/", include("debug_toolbar.urls")), 
]

apis/urls.py
from django.urls import path, include
import apis.views as api_view
from django.contrib import admin
from apis import views
from django.urls import resolve

urlpatterns = [ 
    path('<int:dept_id>/batch', api_view.BatchListByDept.as_view(), name='batch-list-by-dept'),
    path('<int:dept_id>/batch/<int:batch_id>/section', api_view.SectionByDept.as_view()),
    path('<int:dept_id>/batch/<int:batch_id>/section/<int:section_id>/class', api_view.ClassDetailsByDayView.as_view()),
    path('', api_view.DepartmentAll.as_view()),
    
    
]

info/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from .models import *

urlpatterns = [
    path('', views.index, name='index'),

    path('teacher/<slug:teacher_id>/dashboard/',
         views.dashboard, name='dashboard'),

    path('get_departments/', views.get_departments, name='get_departments'),
    path('get_batches/', views.get_batches, name='get_batches'),
    path('get_sections/', views.get_sections, name='get_sections'),

    path('teacher/<slug:teacher_id>/classes/<int:department_id>/<int:batch_id>/<int:section_id>/', views.classes, name='classes'),
    path('teacher/<slug:teacher_id>/classes/', views.all_class_details, name='all_classes'),
    path('teacher/<slug:teacher_id>/classes/<int:department_id>/<int:batch_id>/<int:section_id>/add_class_form/', views.add_class, name='add_class'),
    path('teacher/<slug:teacher_id>/classes/add_class_form/', views.add_class_without_params, name='add_class_without_params'),
    path('teacher/<slug:teacher_id>/classes/<int:class_id>/', views.view_class, name='view_class'),
    path('teacher/<slug:teacher_id>/classes/<int:class_id>/edit/', views.edit_class, name='edit_class'),
    path('teacher/<slug:teacher_id>/classes/<int:class_id>/delete/', views.delete_class, name='delete_class'),

    

    path('buses/uproute/', views.bus_day, name='uproute'),
    path('buses/downroute/', views.bus_day, name='downroute'),
    path('buses/<str:routetype>/<int:busday_id>/', views.busschedule, name='busschedule'),
    path('buses/<str:routetype>/<int:busday_id>/add_bus/', views.add_busschedule, name='add_bus'),
    path('buses/<str:routetype>/<int:busday_id>/view/<int:busschedule_id>/', views.view_busschedule, name='view_busschedule'),
    path('buses/<str:routetype>/<int:busday_id>/<int:busschedule_id>/edit/', views.edit_busschedule, name='edit_busschedule'),
    path('busschedule/delete/<int:busschedule_id>/', views.delete_busschedule, name='delete_busschedule'),
]
admin.site.site_url = None
admin.site.site_header = 'My Site'

info/models.py
import re
from django import forms
from django.db import models
import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from datetime import timedelta

from django.forms import ValidationError




# Create your models here.
sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

time_slots = (
    ('7:30 - 8:30', '7:30 - 8:30'),
    ('8:30 - 9:30', '8:30 - 9:30'),
    ('9:30 - 10:30', '9:30 - 10:30'),
    ('11:00 - 11:50', '11:00 - 11:50'),
    ('11:50 - 12:40', '11:50 - 12:40'),
    ('12:40 - 1:30', '12:40 - 1:30'),
    ('2:30 - 3:30', '2:30 - 3:30'),
    ('3:30 - 4:30', '3:30 - 4:30'),
    ('4:30 - 5:30', '4:30 - 5:30'),
)

DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

test_name = (
    ('Internal test 1', 'Internal test 1'),
    ('Internal test 2', 'Internal test 2'),
    ('Internal test 3', 'Internal test 3'),
    ('Event 1', 'Event 1'),
    ('Event 2', 'Event 2'),
    ('Semester End Exam', 'Semester End Exam'),
)


class User(AbstractUser):

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        return False


class Dept(models.Model):
    
    name = models.CharField(max_length=200, default = "CSE")
    
    

    def __str__(self):
        return self.name
    
        

class Batch(models.Model):
    
    name = models.CharField(max_length=200, default="50")
    department = models.ForeignKey(Dept, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    


class Section(models.Model):
    
    name = models.CharField(max_length=200, default="A")
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    department = models.ForeignKey(Dept, on_delete=models.CASCADE, editable=False, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.department:
            self.department = self.batch.department
        super().save(*args, **kwargs)
    
    
    def __str__(self):
        return self.name
    



class ClassDetails(models.Model):
    department = models.ForeignKey(Dept, on_delete=models.CASCADE)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    classCode = models.CharField(max_length=200, default=None)  # Change "name" to "classCode"
    day = models.CharField(max_length=200, default=None)
    classSubject = models.CharField(max_length=200, default=None)
    classRoom = models.CharField(max_length=200, default=None)
    classStart = models.CharField(max_length=5, default=None)  # Store as 'HH:MM'
    classEnd = models.CharField(max_length=5, default=None)
    teacherInit = models.CharField(max_length=50, default=None)
    

    def __str__(self):
        return self.classCode
    
    """
    def clean_classStart(self):
        classStart = self.cleaned_data.get('classStart')
        if not re.match(r'^\d{2}:\d{2}$', classStart):
            raise forms.ValidationError("Class Start should be in 'HH:MM' format.")
        return classStart
    
    def clean_classEnd(self):
        classEnd = self.cleaned_data.get('classEnd')
        if not re.match(r'^\d{2}:\d{2}$', classEnd):
            raise forms.ValidationError("Class End should be in 'HH:MM' format.")
        return classEnd

    
    def save(self, *args, **kwargs):
        self.clean_classStart(self.classStart)
        self.clean_classEnd(self.classEnd)
        super().save(*args, **kwargs)

"""
class BusDay(models.Model):
    
    day= models.CharField(max_length=10)

    def __str__(self):
        return self.day

class Route(models.Model):
    route_type = models.CharField(max_length=100)

    def __str__(self):
        return self.route_type   
    

class BusSchedule(models.Model):
    day = models.ForeignKey(BusDay, on_delete=models.CASCADE, blank=True, null=True)
    route_type = models.ForeignKey(Route, on_delete=models.CASCADE, null=True, blank=True)
    time_of_day = models.CharField(max_length=10, default=None, null=True, blank=True)
    bus_number = models.CharField(max_length=10)
    route_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.day} - {self.route_type}"


        
class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name


class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)



class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1980-01-01')

    @staticmethod
    def get_total_teachers():
        return Teacher.objects.count()
    def __str__(self):
        return self.name


# Triggers


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)


days = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
}

info/forms.py
import re
from django import forms
from .models import ClassDetails, BusSchedule, BusDay





#------------------- Class Details Form Start-------------------




class ClassDetailsForm(forms.ModelForm):
    class Meta:
        model = ClassDetails
        fields = ['department', 'batch', 'section', 'day', 'classCode', 'classStart', 'classEnd', 'classSubject', 'classRoom', 'teacherInit' ]




            #------------------Format Class start time-------------------



    def clean_classStart(self):
        classStart = self.cleaned_data.get('classStart')
        if not re.match(r'^\d{2}:\d{2}$', classStart):
            raise forms.ValidationError("Class start time should be in 'HH:MM' format.")
        
        return classStart
    
    
            #---------------------------End-----------------------------
    



            #------------------Format Class end time---------------------




    def clean_classEnd(self):
        classEnd = self.cleaned_data.get('classEnd')
        if not re.match(r'^\d{2}:\d{2}$', classEnd):
            raise forms.ValidationError("Class end time should be in 'HH:MM' format.")
        return classEnd
    
    


            #---------------------------End-----------------------------
    




#------------------- Class Details Form End-------------------





#------------------- Bus Schedule Form Start-------------------



    
class BusScheduleForm(forms.ModelForm):
    class Meta:
        model = BusSchedule
        fields = ['day', 'time_of_day', 'bus_number', 'route_name', 'route_type']
    day_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

info/templates/bus/add_bus.html
<style>
   
    .full-width-select {
      width: 100%;
    }
    #id_department {
        width: 100%;
        height: 48px; /* Adjust the height as needed */
        border: 2px solid transparent;
        box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
        border-radius: 6px; /* Add rounded corners */
        padding: 10px; /* Add padding for better spacing */
    }
    
    /* Style the dropdown arrow */
    #id_department::-ms-expand {
        display: none;
    }
  
    #id_batch {
      width: 100%;
      height: 48px; /* Adjust the height as needed */
      border: 2px solid transparent;
      box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
      border-radius: 6px; /* Add rounded corners */
      padding: 10px; /* Add padding for better spacing */
  }
  
  /* Style the dropdown arrow */
  #id_batch::-ms-expand {
      display: none;
  }
  #id_section {
    width: 100%;
    height: 48px; /* Adjust the height as needed */
    border-radius: 6px; /* Add rounded corners */
    padding: 10px; /* Add padding for better spacing */
    border: 2px solid transparent;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  /* Style the dropdown arrow */
  #id_section::-ms-expand {
    display: none;
  }
  custom-day {
    width: 100%;
    height: 48px; /* Adjust the height as needed */
    border-radius: 6px; /* Add rounded corners */
    padding: 10px; /* Add padding for better spacing */
    border: 2px solid transparent;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  /* Style the dropdown arrow */
  #id_day::-ms-expand {
    display: none;
  }
    
  
  #id_classCode {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  #id_classStart {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  #id_day {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
    cursor: not-allowed;
    background-color: #f0f0f0;
    color: #808080;
    
  }
  
  #id_time_of_day {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  #id_bus_number {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  #id_route_name {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  </style>


{% extends 'info/base.html' %}
{% block content %}

{% load static %}


      <div class="page-header">
        <h3 class="page-title"> Add Schedule for {{bus_day}} </h3>
        
      </div>
      <div class="row">
            <div class="col-12">              
                  <div class="card">
                        <div class="card-body">
                          <form method="post">
                            {% csrf_token %}
                            
                            <div class="mb-3 full-width-select">
                            <label for="{{ form.day.id_for_label }}" class="form-label">Day</label>
                            <select id="{{ form.day.id_for_label }}" name="{{ form.day.name }}" class="form-select">
                              {% for day in days %}
                              <option value="{{ day.id }}" {% if day.id == bus_day.id %}selected{% endif %}>
                                  {{ day.day }}
                              </option>
                              {% endfor %}
                          </select>
                      
                            </div>
                            <div class="mb-3 full-width-select">
                                <label for="{{ form.time_of_day.id_for_label }}" class="form-label">Bus Time</label>
                                {{ form.time_of_day}}
                                {% if form.errors.time_of_day %}
        <div style="color: red;">{{ form.errors.time_of_day }}</div>
    {% endif %}
                              </div>
                              <div class="mb-3">
                                <label for="{{ form.bus_number.id_for_label }}" class="form-label">Bus Number</label>
                                {{ form.bus_number }}
                              </div>
                              <div class="mb-3">
                                <label for="{{ form.route_name.id_for_label }}" class="form-label">Route</label>
                                {{ form.route_name }}
                              </div>
                              
                              <button type="submit" class="btn btn-primary btn-submit">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
            </div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> 

<script>
    var myElement = document.getElementById("{{ form.day.id_for_label }}");
        
    myElement.style.pointerEvents = "none";

</script> 



        {% endblock %}

info/templates/bus/buses.html
{% extends 'info/base.html' %}
{% block content %}
    

{% load static %}


    
      <div class="page-header">
        <h3 class="page-title">
          <span class="page-title-icon bg-gradient-primary text-white me-2">
            <i class="mdi mdi-calendar-multiple-check"></i>
          </span> Bus days
        </h3>
      </div>
      <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <div class="col-md-4">
          

          </div>
              <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                      <th>No</th>
                      <th>   </th>
                      <th>Day</th>
                      <th>   </th>
                      <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for day in day_objects %}
                    <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>   </td>
                    <td>{{ day.day }}</td>
                    <td>   </td>
                    <td class="action-buttons">
                      <button type="button" onclick="toggleRoute('{{ day.id }}')" class="btn btn-outline-primary btn-fw">
                        Bus Schedules
                    </button>
                  </td>
                    </tr>
                    {% endfor %}
                </tbody>
                  
                  </table>
            </div>
            </div>
          </div>
        </div>
      </div>

      
      <script>
        function toggleRoute(dayId) {
            var currentURL = window.location.pathname;
            var currentRoute = currentURL.includes('uproute') ? 'uproute' : 'downroute';
            var newRoute = currentRoute === 'uproute' ? 'uproute' : 'downroute';
        
            // Check if the current URL already contains a routetype
            if (currentURL.includes('uproute') || currentURL.includes('downroute')) {
                // Replace the current routetype with the new routetype
                currentURL = currentURL.replace(currentRoute, newRoute);
            } else {
                // Add the new routetype to the URL
                currentURL = currentURL + newRoute;
            }
        
            // Build the new URL with the updated routetype and dayId
            var newURL = currentURL + dayId + '/';
        
            // Redirect to the new URL
            window.location.href = newURL;
        }
        </script>

  
  <!-- main-panel ends -->



{% endblock %}

info/templates/bus/delete_busschedule.html
{% extends 'info/base.html' %}
{% block content %}
    

{% load static %}

<h1>Delete Class</h1>
<p>Are you sure you want to delete this class?</p>
<form action="{% url 'delete_busschedule' busschedule.id %}" method="post">
    {% csrf_token %}
    <button type="submit" name="confirm_delete" class="btn btn-danger">Confirm Delete</button>
    <a href="#" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

info/templates/bus/edit_busschedule.html
<style>
   
    .full-width-select {
      width: 100%;
    }
    #id_department {
        width: 100%;
        height: 48px; /* Adjust the height as needed */
        border: 2px solid transparent;
        box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
        border-radius: 6px; /* Add rounded corners */
        padding: 10px; /* Add padding for better spacing */
    }
    
    /* Style the dropdown arrow */
    #id_department::-ms-expand {
        display: none;
    }
  
    #id_batch {
      width: 100%;
      height: 48px; /* Adjust the height as needed */
      border: 2px solid transparent;
      box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
      border-radius: 6px; /* Add rounded corners */
      padding: 10px; /* Add padding for better spacing */
  }
  
  /* Style the dropdown arrow */
  #id_batch::-ms-expand {
      display: none;
  }
  #id_section {
    width: 100%;
    height: 48px; /* Adjust the height as needed */
    border-radius: 6px; /* Add rounded corners */
    padding: 10px; /* Add padding for better spacing */
    border: 2px solid transparent;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  /* Style the dropdown arrow */
  #id_section::-ms-expand {
    display: none;
  }
  #id_day {
    width: 100%;
    height: 48px; /* Adjust the height as needed */
    border-radius: 6px; /* Add rounded corners */
    padding: 10px; /* Add padding for better spacing */
    border: 2px solid transparent;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  /* Style the dropdown arrow */
  #id_day::-ms-expand {
    display: none;
  }
    
  
  #id_classCode {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  #id_classStart {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  #id_classEnd {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  #id_classSubject {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  #id_classRoom {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  
  #id_teacherInit {
    width: 100%;
    height: 48px;
    border: 2px solid transparent;
    border-radius: 6px;
    padding: 10px;
    font-size: 16px;
    box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
  }
  </style>

{% extends 'info/base.html' %}
{% block content %}

<h2>Edit Class Details</h2>

<div class="page-header">
    <h3 class="page-title"> Form elements </h3>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Forms</a></li>
        <li class="breadcrumb-item active" aria-current="page">Form elements</li>
      </ol>
    </nav>
  </div>
  <div class="row">
    <div class="col-12">              
                      <div class="card">
                        <div class="card-body">
    <form class="form-sample" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary btn-submit">Save Changes</button>
        <a href="{% url 'view_busschedule' routetype=busschedule.route_type busday_id=busschedule.day.id busschedule_id=busschedule.id %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
</div>
</div>
</div>



    {% endblock %}

info/templates/bus/view_busschedule.html
{% extends 'info/base.html' %}
{% block content %}



            <div class="modal-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Day</th>
                            <td>{{ busschedule.day }}</td>
                        </tr>
                        <tr>
                            <th>Time</th>
                            <td>{{ busschedule.time_of_day }}</td>
                        </tr>
                        <tr>
                            <th>Bus Number</th>
                            <td>{{ busschedule.bus_number }}</td>
                        </tr>
                        <tr>
                            <th>Route Name</th>
                            <td>{{ busschedule.route_name }}</td>
                        </tr>
                        <tr>
                            
                        <!-- Add more fields here -->
                    </tbody>
                </table>
            </div>
            



    {% endblock %}